<?php

return [
    'dietary_tags' => [
        'vegetarian',
        'vegan',
        'gluten-free',
        'high-fiber',
        'heart-healthy',
        'probiotic',
        'calcium-rich',
        'healthy-fats',
        'omega-3-rich',
        'high-protein',
        'mediterranean',
        'low-fat',
        'low-sodium',
        'low-carb',
        'keto-friendly',
        'low-calorie',
    ],
    'health_benefits' => [
        'High fiber',
        'Antioxidants',
        'Heart-healthy',
        'Blood pressure support',
        'Probiotics',
        'Bone health',
        'Calcium-rich',
        'High protein',
        'Healthy fats',
        'Energy boost',
        'Potassium-rich',
        'Omega-3',
        'Complete protein',
        'Low glycemic',
        'Balanced nutrition',
        'Plant-based protein',
        'Lean protein',
        'Low saturated fat',
        'Plant protein',
        'Cholesterol reduction',
        'Muscle building',
        'Iron-rich',
        'Vitamin A',
        'Vitamins',
        'Energy',
    ],
];